### ISSUE TITLE
Beta 2 final Roadmap

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#252]
Using this to communicate / discuss prioritization.

**Comment by michael** [comment]
First thing to decide: When should we push the release button? :)

I would suggest that we use this week for polish and target Friday. So we can soft-launch over the weekend and we start to promote it on Moday?

**Comment by obuchtala** [comment]
Agreed.

**Comment by obuchtala** [comment]
Next I want to work on several core related issues:
- [x] #247 - Fix Clipboard
  Fixed in a first iteration. In Beta 3 I will refine this work: #271
- [x] #186 - Allow TextPropertyComponent outside of Surface context
- [x] #179 - Component: Incremental update API should support .append('string')
- [x] #161 - Ability to call extend without proto
  Class.extend can be considered now as a replacement for `oo.inherit` removing the `oo` imports
  all over the place
- [x] #138 - PathAdapter.get returns root when it should return undefined
- [x] #123 - Remove DocumentNode attach/detach API
- [x] #118 - Fragmenter should treat cursor annotations as atomic

**Comment by michael** [comment]
That would be nice if could cover those! 

I will think about my roadmap and post until tomorrow. I want to adapt the new CSS naming scheme to all components we have. And of course having a useful subset of components properly documented.

**Comment by michael** [comment]
My plan (in that order):
- [x] #243 - Bring back block node display
- [x] #178 - Code, Subscript, Superscript node types
- [x] #167 consistent node type categorization (after new node api is ready)
- [ ] #185 - API docs
- [x] #244 - update website

**Comment by obuchtala** [comment]
:+1: go for it

**Comment by obuchtala** [comment]
Skipped:  #127 - Use a simplified surface transaction API

  Having trouble to implement this simplification. Using explicit args in transforms means
  that transforms need to pass through any arguments necessary for children
  even if they don't make sense there. Adding a more detailed explanation to the issue.
  Shifted to Beta 3

**Comment by obuchtala** [comment]
@michael we could extend shift the public release day by 2 days so that we can do a good iteration on Lens dev to validate if the release is good enough?

**Comment by michael** [comment]
Wanted to suggest that as well.

**Comment by michael** [comment]
Let's just take some more time to round it up and do more testing. We did a lot of breaking API changes.

**Comment by obuchtala** [comment]
I think the point is that the release should be out before we come to SF.
And of course, we should focus next week on making Lens as good as possible - so after today we should freeze features.

**Comment by obuchtala** [comment]
Removed this from your list:
- [ ] #60 - improve setHighlights API
